#pragma once
class DynamicArray
{
public:
	DynamicArray();		//constructor
	~DynamicArray();	//destructor

	//ASSIGNMENT OPERATOR:

	//COPY CONSTRUCTOR:

	//FUNCTIONS FOR ADDING AND REMOVING FROM THE END OF THE ARRAY

	//FUNCTIONS FOR ADDING 1 OR MORE ELEMENTS FROM THE MIDDLE OF THE ARRAY

	//FUNCTIONS FOR REMOVING FROM THE MIDDLE OF THE ARRAY, WITH BOTH ORDERED AND UNORDERED REMOVAL

	//FUNCTIONS FOR CHANGING HOW MUCH SPACE IS ALLOCATED FOR THE ARRAY

	//A FUNCTION FOR CLEARING THE ARRAY
	

};

